### ISSUE TITLE
Support for X-Up-Fail-Target

### ISSUE THREAD

**Issue by triskweline** [adam12/roda-unpoly#1]
Just a heads up that the new Unpoly 0.50.0 release adds a new `X-Up-Fail-Target` header. It contains the selector that will be updated in case of a failed (non-2xx) response.

Here is the commit that adds `up.fail_target`, `up.fail_target?` and `up.any_target?` to the Rails bindings:
https://github.com/unpoly/unpoly/commit/f3e8df2c7b0280ad5899e1db58a17cf0fcde37b5

**Comment by adam12** [comment]
Thanks for the notice. I was wondering if there were any protocol changes.
